# Configuration des garde-fous pre-commit
repos:
  # --- 1. Sécurité : Détection de secrets et clés privées ---
  - repo: local
    hooks:
      - id: gitleaks
        name: detect hardcoded secrets (gitleaks)
        entry: gitleaks detect --no-git --verbose --redact
        language: system
        pass_filenames: false
  # --- 2. Hygiène générale des fichiers et code ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
        args: ['--fix=lf']

  # --- 3. DevOps : Qualité et bonnes pratiques Docker ---
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker

  # --- 4. Convention : Normalisation des messages de commit ---
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
